
package com.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IHelloWorld", targetNamespace = "http://service.ws.maven.nyx.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHelloWorld {


    /**
     * 
     * @return
     *     returns com.ws.MapConvertor
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMapInfo", targetNamespace = "http://service.ws.maven.nyx.com/", className = "com.ws.GetMapInfo")
    @ResponseWrapper(localName = "getMapInfoResponse", targetNamespace = "http://service.ws.maven.nyx.com/", className = "com.ws.GetMapInfoResponse")
    public MapConvertor getMapInfo();

    /**
     * 
     * @param message
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.ws.maven.nyx.com/", className = "com.ws.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.ws.maven.nyx.com/", className = "com.ws.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "message", targetNamespace = "")
        String message);

    /**
     * 
     * @return
     *     returns java.util.List<com.ws.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUserArr", targetNamespace = "http://service.ws.maven.nyx.com/", className = "com.ws.GetAllUserArr")
    @ResponseWrapper(localName = "getAllUserArrResponse", targetNamespace = "http://service.ws.maven.nyx.com/", className = "com.ws.GetAllUserArrResponse")
    public List<User> getAllUserArr();

    /**
     * 
     * @return
     *     returns java.util.List<com.ws.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUser", targetNamespace = "http://service.ws.maven.nyx.com/", className = "com.ws.GetAllUser")
    @ResponseWrapper(localName = "getAllUserResponse", targetNamespace = "http://service.ws.maven.nyx.com/", className = "com.ws.GetAllUserResponse")
    public List<User> getAllUser();

}
